# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

fastlane_require 'dotenv'

before_all do
  Dotenv.overload '../../.env'
end


default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    ensure_git_branch(branch: 'v2')
    increment_build_number(xcodeproj: "PRODEMO.xcodeproj")
    build_app(workspace: "PRODEMO.xcworkspace", scheme: "PRODEMO", configuration: "Release", export_options: {
      method: "app-store",
      provisioningProfiles: {
        "com.kapusons.prodemo" => "Prodemo 3"
      }
    })
    upload_to_testflight
  end

  desc "Push a new build to App Store"
  lane :deploy do
    ensure_git_branch(branch: 'develop')
    increment_build_number(xcodeproj: "PRODEMO.xcodeproj")
    build_app(workspace: "PRODEMO.xcworkspace", scheme: "PRODEMO", configuration: "Release", export_options: {
      method: "app-store",
      provisioningProfiles: {
        "com.kapusons.prodemo" => "Prodemo 3"
      }
    })
    upload_to_testflight
  end
end