const LABELS = {
  en: {
    Countries: {
      italy: 'Italy',
      portugal: 'Portugal',
      belgium: 'Belgium',
    },
    Menu: {
      Home: 'Home',
      Articles: 'Articles',
      Events: 'Events',
      Surveys: 'Ask & Answer',
      Info: 'Project info',
      Settings: 'Settings',
      Footer: 'Co-founded by the Rights, Equality & Citizenship Programme of the European Union',
      Notifications: 'Notifications',
      Profile: 'Profile',
      SignIn: 'SignIn/SignUp',
      Logout: 'Logout',
      AddEvent: 'Add event',
      AddSurvey: 'Add survey',
      Sign_in: 'Sign in',
      Sign_up: 'Sign up',
      Forgot_password: 'Forgot password',
      Reset_password: 'Reset password',
      Reset_password_success: 'Reset password',
    },
    Home: {
      ReadLastArticles: 'Read the last articles',
      GetInvolved: 'Get involved in your country',
      ExploreEvents: 'Explore all events',
      ExploreSurveys: 'Ask & Answer',
      ReadMore: 'Read more...',
    },
    Article: {
      Article: 'Article',
      NoArticles: 'No articles for this country',
      AlertTitle: 'This article is in a country different from your country settings',
      AlertMessage: 'Change the country settings if you want to see this article in your list.',
    },
    Event: 'Event',
    Events: {
      Map: 'Map',
      Calendar: 'Calendar',
      User: 'Your events',
      LocaleConfig: {
        monthNames: [
          'January',
          'February',
          'March',
          'April',
          'May',
          'June',
          'July',
          'August',
          'September',
          'October',
          'November',
          'December',
        ],
        monthNamesShort: [
          'Jan',
          'Feb',
          'Mar',
          'Apr',
          'May',
          'Jun',
          'Jul',
          'Aug',
          'Sep',
          'Oct',
          'Nov',
          'Dec',
        ],
        dayNames: [
          'Sun',
          'Mon',
          'Tue',
          'Wed',
          'Thu',
          'Fri',
          'Sat',
        ],
        dayNamesShort: [
          'Sun',
          'Mon',
          'Tue',
          'Wed',
          'Thu',
          'Fri',
          'Sat',
        ],
      },
      NoEventsAll: 'No events for this country',
      NoEvents: 'No events for this date',
      CheckLink: 'Open link',
      AlertTitle: 'This event is in a country different from your country settings',
      AlertMessage: 'Change the country settings if you want to see this event in your list.',
      CheckPermissions: 'Permission denied',
      PermissionInstructions: 'Seems that you have denied permission to access Calendar. Go to Settings -> PRODEMO and enable Calendar permissions before saving the event.',
      AddToCalendarTitle: 'Add event to Calendar',
      AddToCalendarSub: 'Do you want to add this event to your Calendar?',
      RemoveFromCalendarTitle: 'Remove from Calendar',
      RemoveFromCalendarSub: 'Do you want to remove this event from your Calendar?',
      EventTypeUser: 'User event',
      EventTypeAdmin: 'Admin event',
      EventStatusPending: 'Status: Pending',
      EventStatusRejected: 'Status: Rejected',
      AddEvent: 'Add event',
      CreateEvent: {
        Header: 'Submit a new event',
        Date: 'Date',
        Title: 'Title',
        Abstract: 'Short description',
        Description: 'Long description',
        Address: 'Address N°, City, Country',
        Link: 'Link',
        Submit: 'Submit',
        EventCreated: 'Event created!',
        SubmitText: 'By clicking "Submit" your event will be sent to an admin for review. You can check the status inside Events -> Your events page.',
        DatePicker: 'Select a date',
        DatePickerCancel: 'Cancel',
        DatePickerConfirm: 'Confirm',
      },
      OpenOnMaps: 'Open on Google Maps',
    },
    Surveys: {
      Answers: 'answers',
      Vote: 'vote',
      Votes: 'votes',
      Survey: 'Survey',
      List: 'All surveys',
      User: 'Your surveys',
      PickAnswer: 'Pick your answer',
      AlreadyVoted: 'You have already voted',
      AddSurvey: {
        Add: 'Add new',
        Header: 'Submit a new survey',
        Answer: 'Answer',
        AddAnswer: 'Add answer',
        SurveyCreated: 'Survey created!',
        SubmitText: 'By clicking "Submit" your survey will be sent to an admin for review. You can check the status inside Ask & Answer -> Your surveys page.',
      },
    },
    Info: {
      TheProject: 'The Project',
      ProjPartners: 'Project Partners',
      Description: 'PRODEMO is a project co-founded by the Rights, Equality & Citizenship (REC) program of the European Union, to improve the awareness on EU citizenship right and inclusion of mobile EU citizens.',
    },
    IntroSettings: {
      GenralInfo: 'General informations',
      AppLang: 'Application language',
      ChooseCountry: 'Choose a country',
      ChangeCountry: 'Change country',
      Activate: 'Activate',
      Deactivate: 'Deactivate',
    },
    NoNotifications: 'All\'s quiet here 😴',
    WalkThrough: {
      Skip: 'Skip',
      TitleFirst: 'Select your country',
      TitleSecond: 'Select your language',
      ContentSecond: 'Choose what you care and get involved',
      TitleThird: 'Stay tuned!',
      GetStarted: 'Get started',
    },
    ShareLink: 'Download PRODEMO and take a look at this new',
    SignIn: {
      Email: 'Email',
      Password: 'Password',
      ForgotPassword: 'Forgot password?',
      Or: 'or',
      SignFacebook: 'Sign in with Facebook',
      SignGoogle: 'Sign in with Google',
      SignApple: 'Sign in with Apple',
      Cancel: 'Cancel',
      SignIn: 'Sign in',
      SignUp: 'Sign up',
      NotAccount: 'Don’t have an account? Sign up',
      NoInfoTitle: 'Something went wrong!',
    },
    SignUp: {
      ChooseRegion: 'Choose a region...',
      ValidationErrorTitle: 'Validation error!',
      PasswordShort: 'Your password must be 6 characters long at least',
      ValidationErrorMessage: 'Something went wrong. Check your data or go back and try to sign in.',
      JoinTitle: 'Welcome to PRODEMO!',
      JoinMessage: 'Sign up and get involved inside the European community!',
      Username: 'Username',
      Policy_1: 'I have read and agree to the',
      Policy_2: 'privacy policy',
      Policy_Url: 'https://www.prodemo-europa.eu/app-privacy-policy/',
    },
    ForgotPassword: {
      Text: 'Do not worry! We will help you recover your password 🔑',
      SendEmail: 'Send email',
      ConfirmationSent: 'Confirmation sent!',
      Confirmation_1: 'We have sent and email at',
      Confirmation_2: 'with a link for password reset',
      Wrong_1: 'Make sure that',
      Wrong_2: 'is the correct email or that is associated with an existing account',
    },
    ResetPassword: {
      RePassword: 'Re-Password',
      Title: 'Reset Password',
      Text: 'Please enter your new password 🔑',
      Button: 'Set new password',
      ErrorText: 'Fill both fields with the same password and try again',
    },
    EmailPasswordSuccess: {
      Password: 'Password changed!',
      PasswordText: 'Thanks 🎉 your password was reset!',
      Email: 'Email verified!',
      EmailText: 'Thanks 🎉 your email was confirmed!',
      BackHome: 'Back home',
    },
    Profile: {
      Welcome: 'Welcome',
    },
    Report: {
      TextTop: 'You can report directly from an individual event or survey for certain violations, including: spam, abusive or harmful content, inappropriate ads, self-harm and fake news.',
      Title: 'Report violation',
      Type: 'Type your message',
      Send: 'Send report',
      MessageSent: 'Message sent! An admin will check your report.',
    },
  },
  it: {
    Countries: {
      italy: 'Italia',
      portugal: 'Portogallo',
      belgium: 'Belgio',
    },
    Menu: {
      Home: 'Home',
      Articles: 'Articoli',
      Events: 'Eventi',
      Surveys: 'Sondaggi',
      Info: 'Informazioni sul progetto',
      Settings: 'Impostazioni',
      Footer: 'Cofinanziato dal Programma Diritti, Uguaglianza e Cittadinanza dell’Unione Europea',
      Notifications: 'Notifiche',
      Profile: 'Profilo',
      SignIn: 'Accedi/Iscriviti',
      Logout: 'Logout',
      AddEvent: 'Crea evento',
      AddSurvey: 'Crea sondaggio',
      Sign_in: 'Accedi',
      Sign_up: 'Iscriviti',
      Forgot_password: 'Password dimenticata',
      Reset_password: 'Reimposta la password',
      Reset_password_success: 'Reimposta la password',
    },
    Home: {
      ReadLastArticles: 'Leggi gli ultimi articoli',
      GetInvolved: 'Partecipa agli eventi del tuo paese',
      ExploreEvents: 'Scopri tutti gli eventi',
      ExploreSurveys: 'Sondaggi',
      ReadMore: 'Scopri di più…',
    },
    Article: {
      Article: 'Articolo',
      NoArticles: 'Nessun articolo per questo paese',
      AlertTitle: 'Questo articolo riguarda un paese diverso da quello che hai selezionato',
      AlertMessage: 'Modifica il paese nelle tue impostazioni se vuoi vedere questo articolo nella lista',
    },
    Event: 'Evento',
    Events: {
      Map: 'Mappa',
      Calendar: 'Calendario',
      User: 'I tuoi eventi',
      LocaleConfig: {
        monthNames: [
          'Gennaio',
          'Febbraio',
          'Marzo',
          'Aprile',
          'Maggio',
          'Giugno',
          'Luglio',
          'Agosto',
          'Settembre',
          'Ottobre',
          'Novembre',
          'Dicembre',
        ],
        monthNamesShort: [
          'Gen',
          'Feb',
          'Mar',
          'Apr',
          'Mag',
          'Giu',
          'Lug',
          'Ago',
          'Set',
          'Ott',
          'Nov',
          'Dic',
        ],
        dayNames: [
          'Domenica',
          'Lunedì',
          'Martedì',
          'Mercoledì',
          'Giovedì',
          'Venerdì',
          'Sabato',
        ],
        dayNamesShort: [
          'Dom',
          'Lun',
          'Mar',
          'Mer',
          'Gio',
          'Ven',
          'Sab',
        ],
      },
      NoEventsAll: 'Nessun evento per questo paese',
      NoEvents: 'Nessun evento in questa data',
      CheckLink: 'Apri link',
      AlertTitle: 'Questo evento riguarda un paese diverso da quello che hai selezionato',
      AlertMessage: 'Modifica il paese nelle impostazioni per vedere questo evento nella tua lista in futuro.',
      CheckPermissions: 'Permesso negato',
      PermissionInstructions: 'Sembra che ti sia stato negato il permesso di accedere al Calendario. Vai in Impostazioni -> PRODEMO e abilita i permessi di Calendar prima di salvare l\'evento.',
      AddToCalendarTitle: 'Aggiungi questo evento al calendario',
      AddToCalendarSub: 'Vuoi aggiungere questo evento al tuo calendario?',
      RemoveFromCalendarTitle: 'Rimuovi dal calendario',
      RemoveFromCalendarSub: 'Vuoi rimuovere questo evento dal tuo calendario?',
      EventTypeUser: 'Evento utente',
      EventTypeAdmin: 'Evento amministratore',
      EventStatusPending: 'Stato: in attesa di approvazione',
      EventStatusRejected: 'Rifiutato',
      AddEvent: 'Crea evento',
      CreateEvent: {
        Header: 'Proponi un nuovo evento',
        Date: 'Data',
        Title: 'Titolo',
        Abstract: 'Descrizione breve',
        Description: 'Descrizione lunga',
        Address: 'Indirizzo, Città, Nazione',
        Link: 'Link',
        Submit: 'Invia',
        EventCreated: 'Evento creato!',
        SubmitText: 'Facendo clic su "Invia" il tuo evento sarà inviato a un amministratore per la revisione. Puoi controllare lo stato all\'interno della pagina Eventi -> I tuoi eventi.',
        DatePicker: 'Scegli una data',
        DatePickerCancel: 'Annulla',
        DatePickerConfirm: 'Comferma',
      },
      OpenOnMaps: 'Apri in Google Maps',
    },
    Surveys: {
      Answers: 'Risposte',
      Vote: 'Voto',
      Votes: 'Voti',
      Survey: 'Sondaggio',
      List: 'Tutti i sondaggi',
      User: 'I tuoi sondaggi',
      PickAnswer: 'Scegli la tua risposta',
      AlreadyVoted: 'Hai già espresso il tuo voto',
      AddSurvey: {
        Add: 'Crea nuovo',
        Header: 'Crea un nuovo sondaggio',
        Answer: 'Risposta',
        AddAnswer: 'Aggiungi risposta',
        SurveyCreated: 'Sondaggio creato!',
        SubmitText: 'Cliccando su "Invia" il tuo sondaggio sarà inviato ad un amministratore per la revisione. Puoi controllare lo stato nella pagina Sondaggi -> I tuoi sondaggi.',
      },
    },
    Info: {
      TheProject: 'Il Progetto',
      ProjPartners: 'Partner',
      Description: 'PRODEMO è un progetto cofinanziato dal programma Diritti, Uguaglianza e Cittadinanza (REC) dell’Unione Europea, per migliorare la consapevolezza dei diritti di cittadinanza dell’UE e l’inclusione dei cittadini dell’UE in mobilità.',
    },
    IntroSettings: {
      GenralInfo: 'Informazioni Generali',
      AppLang: 'Lingua dell\'applicazione',
      ChooseCountry: 'Scegli un paese',
      ChangeCountry: 'Cambia paese',
      Activate: 'Attiva',
      Deactivate: 'Disattiva',
    },
    NoNotifications: 'Nessuna notifica',
    WalkThrough: {
      Skip: 'Salta',
      TitleFirst: 'Select your country',
      TitleSecond: 'Discover the events',
      ContentSecond: 'Choose what you care and get involved',
      TitleThird: 'Stay tuned!',
      GetStarted: 'Get started',
    },
    ShareLink: 'Scarica l\'App PRODEMO e scopri di più',
    SignIn: {
      Email: 'Email',
      Password: 'Password',
      ForgotPassword: 'Password dimenticata?',
      Or: 'o',
      SignFacebook: 'Accedi con Facebook',
      SignGoogle: 'Accedi con Google',
      SignApple: 'Accedi con Apple',
      Cancel: 'Annulla',
      SignIn: 'Accedi',
      SignUp: 'Iscriviti',
      NotAccount: 'Non hai ancora un account? Iscriviti',
      NoInfoTitle: 'Qualcosa è andato storto!',
    },
    SignUp: {
      ChooseRegion: 'Scegli una regione…',
      ValidationErrorTitle: 'Attenzione!',
      PasswordShort: 'La tua password deve contenere almeno 6 caratteri',
      ValidationErrorMessage: 'Qualcosa è andato storto! Controlla i tuoi dati o prova ad accedere.',
      JoinTitle: 'Benvenuto su PRODEMO!',
      JoinMessage: 'Iscriviti e partecipa nella comunità europea!',
      Username: 'Username',
      Policy_1: 'Ho letto e accetto la',
      Policy_2: 'privacy policy',
      Policy_Url: 'https://www.prodemo-europa.eu/app-privacy-policy/',
    },
    ForgotPassword: {
      Text: 'Non preoccuparti! Ti aiuteremo a recuperare la tua password 🔑',
      SendEmail: 'Invia email',
      ConfirmationSent: 'Conferma inviata!',
      Confirmation_1: 'Abbiamo inviato una mail all\'indirizzo',
      Confirmation_2: 'con un link per ripristinare la password',
      Wrong_1: 'Assicurati che l\'indirizzo',
      Wrong_2: 'sia corretto o che sia associato ad un account esistente',
    },
    ResetPassword: {
      RePassword: 'Reinserisci password',
      Title: 'Reset password',
      Text: 'Inserisci una nuova password 🔑',
      Button: 'Imposta nuova password',
      ErrorText: 'Compila entrambi i campi con la stessa password e riprova',
    },
    EmailPasswordSuccess: {
      Password: 'Password cambiata',
      PasswordText: 'Grazie 🎉 la tua password è stata reimpostata!',
      Email: 'Email verificata!',
      EmailText: 'Grazie 🎉 la tua mail è stata confermata!',
      BackHome: 'Torna alla home',
    },
    Profile: {
      Welcome: 'Benvenuto',
    },
    Report: {
      TextTop: 'Puoi segnalare direttamente da un singolo evento o sondaggio alcune violazioni, tra cui: spam, contenuti abusivi o dannosi, annunci inappropriati, autolesionismo e fake news.',
      Title: 'Segnala una violazione',
      Type: 'Scrivi il tuo messaggio',
      Send: 'Invia segnalazione',
      MessageSent: 'Messaggio inviato! Un amministratore verificherà la tua segnalazione.',
    },
  },
  es: {
    Countries: {
      italy: 'Italia',
      portugal: 'Portugal',
      belgium: 'Bélgica',
    },
    Menu: {
      Home: 'Inicio',
      Articles: 'Artículos',
      Events: 'Eventos',
      Surveys: 'Encuestas',
      Info: 'Información sobre el proyecto',
      Settings: 'Ajustes',
      Footer: 'Cofinanciado por el Programa Derechos, Igualdad y Ciudadanía de la Unión Europea',
      Notifications: 'Notificaciones',
      Profile: 'Perfil',
      SignIn: 'Accede/Inscríbete',
      Logout: 'Final de sesión',
      AddEvent: 'Crea evento',
      AddSurvey: 'Crea encuesta',
      Sign_in: 'Accede  ',
      Sign_up: 'Inscríbete',
      Forgot_password: 'Contraseña olvidada',
      Reset_password: 'Restablece la contraseña',
      Reset_password_success: 'Restablece la contraseña',
    },
    Home: {
      ReadLastArticles: 'Lee los últimos artículos',
      GetInvolved: 'Participa en los eventos de tu país',
      ExploreEvents: 'Descubre todos los eventos',
      ExploreSurveys: 'Encuestas',
      ReadMore: 'Lee más…',
    },
    Article: {
      Article: 'Artículo',
      NoArticles: 'No hay artículos para este país',
      AlertTitle: 'Este artículo se refiere a un país diferente de lo que has seleccionado',
      AlertMessage: 'Modifica el país en los ajustes si quieres ver este artículo en tu lista',
    },
    Event: 'Evento',
    Events: {
      Map: 'Mapa',
      Calendar: 'Calendario',
      User: 'Tus eventos',
      LocaleConfig: {
        monthNames: [
          'Enero',
          'Febrero',
          'Marzo',
          'Abril',
          'Mayo',
          'Junio',
          'Julio',
          'Agosto',
          'Septiembre',
          'Octubre',
          'Noviembre',
          'Diciembre',
        ],
        monthNamesShort: [
          'Ene ',
          'Feb ',
          'Mar ',
          'Abr ',
          'May ',
          'Jun ',
          'Jul ',
          'Ago ',
          'Sep ',
          'Oct ',
          'Nov ',
          'Dic ',
        ],
        dayNames: [
          'Domingo',
          'Lunes',
          'Martes',
          'Miércoles',
          'Jueves',
          'Viernes',
          'Sabado',
        ],
        dayNamesShort: [
          'Dom ',
          'Lun ',
          'Mar ',
          'Mie ',
          'Jue ',
          'Vie ',
          'Sab ',
        ],
      },
      NoEventsAll: 'No hay eventos para este país',
      NoEvents: 'No hay eventos en esta fecha',
      CheckLink: 'Abre el enlace',
      AlertTitle: 'Este evento se refiere a un país distinto al que has seleccionado',
      AlertMessage: 'Modifica el país en los ajustes si quieres ver este evento en tu lista',
      CheckPermissions: 'Permiso denegado',
      PermissionInstructions: 'Parece que te haya sido denegado el permiso para acceder al Calendario. Ir a Ajustes -> PRODEMO y habilitar los permisos de Calendar antes de guardar el evento',
      AddToCalendarTitle: 'Añade este evento al calendario',
      AddToCalendarSub: '¿Quieres añadir este evento a tu calendario?',
      RemoveFromCalendarTitle: 'Elimina del calendario',
      RemoveFromCalendarSub: '¿Quieres eliminar este evento de tu calendario?',
      EventTypeUser: 'Evento usuario',
      EventTypeAdmin: 'Evento administrador',
      EventStatusPending: 'Estado: a la espera de aprobación',
      EventStatusRejected: 'Rechazado',
      AddEvent: 'Crea evento',
      CreateEvent: {
        Header: 'Propón un nuevo evento',
        Date: 'Fecha',
        Title: 'Título',
        Abstract: 'Descripción breve',
        Description: 'Descripción larga',
        Address: 'Dirección, Ciudad, País',
        Link: 'Enlace',
        Submit: 'Envía',
        EventCreated: '¡Evento creado!',
        SubmitText: 'Haciendo clic en "Envía" se enviará tu evento a un administrador para la revisión. Puedes controlar el estado en el interior de la página Eventos -> Tus eventos.',
        DatePicker: 'Elige una fecha',
        DatePickerCancel: 'Anula',
        DatePickerConfirm: 'Confirma',
      },
      OpenOnMaps: 'Abre en Google Maps',
    },
    Surveys: {
      Answers: 'Respuestas',
      Vote: 'Nota',
      Votes: 'Notas',
      Survey: 'Encuesta ',
      List: 'Todas las encuestas',
      User: 'Tus encuestas',
      PickAnswer: 'Elige tu respuesta',
      AlreadyVoted: 'Ya has dado tu nota',
      AddSurvey: {
        Add: 'Crea nueva',
        Header: 'Crea una encuesta nueva',
        Answer: 'Respuesta ',
        AddAnswer: 'Añade respuesta',
        SurveyCreated: '¡Encuesta creada!',
        SubmitText: 'Haciendo clic en "Envía" se enviará tu encuesta a un administrador para la revisión. Puedes controlar el estado en la página Encuestas -> Tus encuestas.',
      },
    },
    Info: {
      TheProject: 'El Proyecto',
      ProjPartners: 'Partner',
      Description: 'PRODEMO es un proyecto cofinanciado por el Programa Derechos, Igualdad y Ciudadanía (REC) de la Unión Europea, para mejorar el conocimiento de los derechos de ciudadanía de la UE y la inclusión de los ciudadanos de la UE en movimiento. ',
    },
    IntroSettings: {
      GenralInfo: 'Información General',
      AppLang: 'Idioma de la aplicación',
      ChooseCountry: 'Elige un país',
      ChangeCountry: 'Cambia país',
      Activate: 'Activa',
      Deactivate: 'Desactiva',
    },
    NoNotifications: 'Ninguna notificación',
    WalkThrough: {
      Skip: 'Saltar',
      TitleFirst: 'Elige tu país',
      TitleSecond: 'Descubre los eventos',
      ContentSecond: 'Choose what you care and get involved',
      TitleThird: 'Stay tuned!',
      GetStarted: 'Get started',
    },
    ShareLink: 'Descarga la App PRODEMO y descubre más',
    SignIn: {
      Email: 'Correo electrónico',
      Password: 'Contraseña  ',
      ForgotPassword: '¿Has olvidado la contraseña?',
      Or: 'o',
      SignFacebook: 'Accede con Facebook',
      SignGoogle: 'Accede con Google',
      SignApple: 'Accede con Apple',
      Cancel: 'Anula',
      SignIn: 'Accede',
      SignUp: 'Inscríbete',
      NotAccount: '¿Aún no tienes una cuenta? Inscríbete',
      NoInfoTitle: '¡Algo salió mal!',
    },
    SignUp: {
      ChooseRegion: 'Elige una región…',
      ValidationErrorTitle: '¡Atención!',
      PasswordShort: 'Tu contraseña debe tener al menos 6 caracteres',
      ValidationErrorMessage: '¡Algo salió mal! Controla tus datos o intenta acceder.',
      JoinTitle: '¡Bienvenido a PRODEMO!',
      JoinMessage: '¡Inscríbete y participa en la comunidad europea!',
      Username: 'Nombre de usuario',
      Policy_1: 'He leído y acepto la',
      Policy_2: 'política de privacidad',
      Policy_Url: 'https://www.prodemo-europa.eu/app-privacy-policy/',
    },
    ForgotPassword: {
      Text: '¡No te preocupes! Te ayudaremos a recuperar tu contraseña 🔑',
      SendEmail: 'Envía un correo electrónico',
      ConfirmationSent: '¡Confirmación enviada!',
      Confirmation_1: 'Hemos enviado un correo electrónico a la dirección',
      Confirmation_2: 'con un enlace para restablecer la contraseña',
      Wrong_1: 'Asegúrate de que la dirección',
      Wrong_2: 'sea correcta o que esté asociada a una cuenta existente',
    },
    ResetPassword: {
      RePassword: 'Vuelve a introducir la contraseña',
      Title: 'Restablecer la contraseña',
      Text: 'Introduce una contraseña nueva 🔑',
      Button: 'Configura la nueva contraseña',
      ErrorText: 'Rellena ambos campos con la misma contraseña e inténtalo de nuevo',
    },
    EmailPasswordSuccess: {
      Password: 'Contraseña cambiada',
      PasswordText: 'Gracias 🎉, ¡tu contraseña ha sido restablecida!',
      Email: '¡Correo electrónico verificado!',
      EmailText: 'Gracias 🎉, ¡tu correo electrónico ha sido confirmado!',
      BackHome: 'Vuelve a la página de inicio',
    },
    Profile: {
      Welcome: 'Bienvenido',
    },
    Report: {
      TextTop: 'Puedes informar directamente desde un evento o encuesta algunas violaciones, entre las cuales: correo no deseado, contenidos abusivos o dañinos, anuncios inapropiados, dañino para uno mismo y noticias falsas.',
      Title: 'Informa sobre una violación',
      Type: 'Escribe tu mensaje',
      Send: 'Envía informe',
      MessageSent: '¡Mensaje enviado! Un administrador verificará tu informe.',
    },
  },
  fr: {
    Countries: {
      italy: 'Italie',
      portugal: 'Portugal',
      belgium: 'Belgique',
    },
    Menu: {
      Home: 'Home',
      Articles: 'Articles',
      Events: 'Événements',
      Surveys: 'Sondages',
      Info: 'Informations sur le projet',
      Settings: 'Paramètres',
      Footer: 'Cofinancé par le Programme « Droits, égalité et citoyenneté » de l’Union européenne',
      Notifications: 'Notifications',
      Profile: 'Profil',
      SignIn: 'Accéder/S\'inscrire',
      Logout: 'Logout',
      AddEvent: 'Créer événement',
      AddSurvey: 'Créer sondage',
      Sign_in: 'Accéder',
      Sign_up: 'S\'inscrire',
      Forgot_password: 'Mot de passe oublié',
      Reset_password: 'Réinitialiser le mot de passe',
      Reset_password_success: 'Réinitialiser le mot de passe',
    },
    Home: {
      ReadLastArticles: 'Lire les derniers articles',
      GetInvolved: 'Participer aux événements dans votre pays',
      ExploreEvents: 'Découvrir tous les événements',
      ExploreSurveys: 'Sondages',
      ReadMore: 'En savoir plus...',
    },
    Article: {
      Article: 'Article',
      NoArticles: 'Aucun article pour ce pays',
      AlertTitle: 'Cet article concerne un pays différent de celui que vous avez sélectionné',
      AlertMessage: 'Modifiez le pays dans vos paramètres si vous souhaitez voir cet article dans la liste',
    },
    Event: 'Événement',
    Events: {
      Map: 'Carte',
      Calendar: 'Calendrier',
      User: 'Vos événements',
      LocaleConfig: {
        monthNames: [
          'Janvier',
          'Février',
          'Mars',
          'Avril',
          'Mai',
          'Juin',
          'Juillet',
          'Août',
          'Septembre',
          'Octobre',
          'Novembre',
          'Décembre',
        ],
        monthNamesShort: [
          'Jan',
          'Fév',
          'Mar',
          'Avr',
          'Mai',
          'Jun',
          'Jul',
          'Aoû',
          'Sep',
          'Oct',
          'Nov',
          'Déc',
        ],
        dayNames: [
          'Dimanche',
          'Lundi',
          'Mardi',
          'Mercredi',
          'Jeudi',
          'Vendredi',
          'Samedi',
        ],
        dayNamesShort: [
          'Dim',
          'Lun',
          'Mar',
          'Mer',
          'Jeu',
          'Ven',
          'Sam',
        ],
      },
      NoEventsAll: 'Aucun événement pour ce pays',
      NoEvents: 'Aucun événement pour cette date',
      CheckLink: 'Ouvrir le lien',
      AlertTitle: 'Cet événement concerne un pays différent de celui que vous avez sélectionné',
      AlertMessage: 'Modifiez le pays dans vos paramètres pour voir cet événement dans votre liste future.',
      CheckPermissions: 'Accès refusé',
      PermissionInstructions: 'Il semble que l’accès au Calendrier ait été refusé. Aller dans Paramètres -> PRODEMO et activer les autorisations de Calendar avant de sauvegarder l’événement.',
      AddToCalendarTitle: 'Ajouter cet événement au calendrier',
      AddToCalendarSub: 'Vous souhaitez ajouter cet événement à votre calendrier ?',
      RemoveFromCalendarTitle: 'Supprimer du calendrier',
      RemoveFromCalendarSub: 'Vous souhaitez supprimer cet événement de votre calendrier ?',
      EventTypeUser: 'Evénement utilisateur',
      EventTypeAdmin: 'Evénement administrateur',
      EventStatusPending: 'Etat: en attente d\'approbation',
      EventStatusRejected: 'Refusé',
      AddEvent: 'Créer événement',
      CreateEvent: {
        Header: 'Proposer un nouvel événement',
        Date: 'Date',
        Title: 'Titre',
        Abstract: 'Description brève',
        Description: 'Description longue',
        Address: 'Adresse, Ville, Pays',
        Link: 'Lien',
        Submit: 'Envoyer',
        EventCreated: 'Evénement créé!',
        SubmitText: 'En cliquant sur "Envoyer", votre événement sera envoyé à un administrateur pour la révision. Vous pouvez contrôler l\'état à l\'intérieur de la page Événements -> Vos événements.',
        DatePicker: 'Choisir une date',
        DatePickerCancel: 'Annuler',
        DatePickerConfirm: 'Confirmer',
      },
      OpenOnMaps: 'Ouvrir dans Google Maps',
    },
    Surveys: {
      Answers: 'Réponses ',
      Vote: 'Vote',
      Votes: 'Votes',
      Survey: 'Sondage',
      List: 'Tous les sondages',
      User: 'Vos sondages',
      PickAnswer: 'Choisir votre réponse',
      AlreadyVoted: 'Vous avez déjà exprimé votre vote',
      AddSurvey: {
        Add: 'Créer nouveau',
        Header: 'Créer un nouveau sondage',
        Answer: 'Réponse',
        AddAnswer: 'Ajouter réponse ',
        SurveyCreated: 'Sondage créé !',
        SubmitText: 'En cliquant sur "Envoyer", votre sondage sera envoyé à un administrateur pour la révision. Vous pouvez contrôler l\'état à l\'intérieur de la page Sondages -> Vos sondages',
      },
    },
    Info: {
      TheProject: 'Le projet',
      ProjPartners: 'Partenaires',
      Description: 'PRODEMO est un projet cofinancé par le programme « Droits, égalité et citoyenneté » (REC) de l’Union européenne, pour promouvoir la connaissance des droits des citoyens de l’UE et l’inclusion des citoyens de l’UE dans le domaine de la mobilité.',
    },
    IntroSettings: {
      GenralInfo: 'Informations Générales',
      AppLang: 'Langue de l’application',
      ChooseCountry: 'Choisir un pays',
      ChangeCountry: 'Changer le pays',
      Activate: 'Activer',
      Deactivate: 'Désactiver',
    },
    NoNotifications: 'Aucune notification',
    WalkThrough: {
      Skip: 'Passer',
      TitleFirst: 'Sélectionner votre pays',
      TitleSecond: 'Découvrir les événements',
      ContentSecond: 'Choisir sa cause et s’impliquer',
      TitleThird: 'Restez connecté(e) !',
      GetStarted: 'Commencer',
    },
    ShareLink: 'Télécharger l’application PRODEMO pour en savoir plus',
    SignIn: {
      Email: 'E-mail',
      Password: 'Mot de passe',
      ForgotPassword: 'Mot de passe oublié ?',
      Or: 'ou',
      SignFacebook: 'Accéder via Facebook',
      SignGoogle: 'Accéder via Google',
      SignApple: 'Accéder via Apple',
      Cancel: 'Annuler',
      SignIn: 'Accéder',
      SignUp: 'S\'inscrire',
      NotAccount: 'Vous n\'avez pas encore un compte? S\'inscrire',
      NoInfoTitle: 'Il y a eu un problème !',
    },
    SignUp: {
      ChooseRegion: 'Choisir une région…',
      ValidationErrorTitle: 'Attention!',
      PasswordShort: 'Votre mot de passe doit contenir au moins 6 caractères',
      ValidationErrorMessage: 'Il y a eu un problème ! Contrôlez vos données ou essayez à nouveau d\'accéder.',
      JoinTitle: 'Bienvenue chez PRODEMO!',
      JoinMessage: 'S\'inscrire et participer dans la communauté européenne!',
      Username: 'Nom d\'utilisateur',
      Policy_1: 'J\'ai lu et accepté la ',
      Policy_2: 'politique de confidentialité',
      Policy_Url: 'https://www.prodemo-europa.eu/app-privacy-policy/',
    },
    ForgotPassword: {
      Text: 'Ne vous préoccupez pas ! Nous vous aiderons à récupérer votre mot de passe 🔑',
      SendEmail: 'Envoyer e-mail',
      ConfirmationSent: 'Confirmation envoyée!',
      Confirmation_1: 'Nous avons envoyé un e-mail à l\'adresse ',
      Confirmation_2: 'avec un lien pour réinitialiser le mot de passe',
      Wrong_1: 'Veiller à ce que l\'adresse soit',
      Wrong_2: 'correcte ou qu\'elle soit associée à un compte existant',
    },
    ResetPassword: {
      RePassword: 'Saisir à nouveau le mot de passe',
      Title: 'Remettre à zéro le mot de passe',
      Text: 'Saisir un nouveau mot de passe 🔑',
      Button: 'Réinitialisez un nouveau mot de passe',
      ErrorText: 'Remplir les champs avec le même mot de passe et réessayer',
    },
    EmailPasswordSuccess: {
      Password: 'Mot de passe changé',
      PasswordText: 'Merci 🎉 votre mot de passe a été réinitialisé!',
      Email: 'E-mail contrôlé!',
      EmailText: 'Merci 🎉 votre mot de passe a été confirmé!',
      BackHome: 'Retour à la page d\'accueil',
    },
    Profile: {
      Welcome: 'Bienvenue ',
    },
    Report: {
      TextTop: 'Vous pouvez directement signaler certaines violations, à partir d\'un seul événement ou d\'un sondage, parmi lesquels: spam, contenus  abusifs ou préjudiciables, annonces inappropriées, autodestruction et fake news.',
      Title: 'Signaler une violation',
      Type: 'Écrire votre message',
      Send: 'Envoyer communication',
      MessageSent: 'Message envoyé! Un administrateur contrôlera votre communication.',
    },
  },
  pt: {
    Countries: {
      italy: 'Itália',
      portugal: 'Portugal',
      belgium: 'Bélgica',
    },
    Menu: {
      Home: 'Home',
      Articles: 'Artigos',
      Events: 'Eventos',
      Surveys: 'Perguntar e responder',
      Info: 'Informações sobre o projeto',
      Settings: 'Definições',
      Footer: 'Cofinanciado pelo Programa Direitos, Igualdade e Cidadania da União Europeia',
      Notifications: 'Notificações',
      Profile: 'Perfil',
      SignIn: 'Iniciar sessão/Efetuar registo',
      Logout: 'Encerrar sessão',
      AddEvent: 'Adicionar evento',
      AddSurvey: 'Adicionar questionário',
      Sign_in: 'Iniciar sessão',
      Sign_up: 'Efetuar registo',
      Forgot_password: 'Esquecer palavra-passe',
      Reset_password: 'Repor palavra-passe',
      Reset_password_success: 'Repor palavra-passe',
    },
    Home: {
      ReadLastArticles: 'Ler os últimos artigos',
      GetInvolved: 'Participar nos eventos do seu país',
      ExploreEvents: 'Descobrir todos os eventos',
      ExploreSurveys: 'Perguntar e responder',
      ReadMore: 'Saber mais…',
    },
    Article: {
      Article: 'Artigo',
      NoArticles: 'Nenhum artigo para este país',
      AlertTitle: 'Este artigo é relativo a um país diferente daquele que selecionou',
      AlertMessage: 'Modifique o país nas suas definições se pretender ver este artigo na lista',
    },
    Event: 'Evento',
    Events: {
      Map: 'Mapa',
      Calendar: 'Calendário',
      User: 'Os seus eventos',
      LocaleConfig: {
        monthNames: [
          'Janeiro',
          'Fevereiro',
          'Março',
          'Abril',
          'Maio',
          'Junho',
          'Julho',
          'Agosto',
          'Setembro',
          'Outubro',
          'Novembro',
          'Dezembro',
        ],
        monthNamesShort: [
          'Jan',
          'Fev',
          'Mar',
          'Abr',
          'Mai',
          'Jun',
          'Jul',
          'Ago',
          'Set',
          'Out',
          'Nov',
          'Dez',
        ],
        dayNames: [
          'Domingo',
          'Segunda-feira',
          'Terça-feira',
          'Quarta-feira',
          'Quinta-feira',
          'Sexta-feira',
          'Sábado',
        ],
        dayNamesShort: [
          'Dom',
          'Seg',
          'Ter',
          'Qua',
          'Qui',
          'Sex',
          'Sáb',
        ],
      },
      NoEventsAll: 'Nenhum evento para este país',
      NoEvents: 'Nenhum evento nesta data',
      CheckLink: 'Abrir ligação',
      AlertTitle: 'Este evento é relativo a um país diferente daquele que selecionou',
      AlertMessage: 'Modifique o país nas definições para, futuramente, ver este evento na sua lista.',
      CheckPermissions: 'Autorização negada',
      PermissionInstructions: 'Parece que lhe foi negada a autorização para aceder ao Calendário. Vá a Definições -> PRODEMO e ative as autorizações de Calendário antes de guardar o evento.',
      AddToCalendarTitle: 'Adicionar este evento ao calendário',
      AddToCalendarSub: 'Pretende adicionar este evento ao seu calendário?',
      RemoveFromCalendarTitle: 'Remover do calendário',
      RemoveFromCalendarSub: 'Pretende remover este evento do seu calendário?',
      EventTypeUser: 'Evento do utilizador',
      EventTypeAdmin: 'Evento do administrador',
      EventStatusPending: 'Estado: pendente',
      EventStatusRejected: 'Estado: recusado',
      AddEvent: 'Adicionar evento',
      CreateEvent: {
        Header: 'Submeter um novo evento',
        Date: 'Data',
        Title: 'Título',
        Abstract: 'Breve descrição',
        Description: 'Descrição longa',
        Address: 'Morada, n.º, cidade, país',
        Link: 'Ligação',
        Submit: 'Submeter',
        EventCreated: 'Evento criado!',
        SubmitText: 'Ao clicar em "Submeter" o seu evento será enviado a um administrador para análise. Pode verificar o estado em Eventos > A sua página de eventos.',
        DatePicker: 'Selecione uma data',
        DatePickerCancel: 'Cancelar',
        DatePickerConfirm: 'Confirmar',
      },
      OpenOnMaps: 'Abrir no Google Maps',
    },
    Surveys: {
      Answers: 'respostas',
      Vote: 'voto',
      Votes: 'votos',
      Survey: 'Questionário',
      List: 'Todos os questionários',
      User: 'Os seus questionários',
      PickAnswer: 'Escolha a sua resposta',
      AlreadyVoted: 'Já votou',
      AddSurvey: {
        Add: 'Adicionar novo',
        Header: 'Submeter um novo questionário',
        Answer: 'Resposta',
        AddAnswer: 'Adicionar resposta',
        SurveyCreated: 'Questionário criado!',
        SubmitText: 'Ao clicar em "Submeter" o seu evento será enviado a um administrador para análise. Pode verificar o estado em Perguntar e responder > A sua página de questionários.',
      },
    },
    Info: {
      TheProject: 'O Projeto',
      ProjPartners: 'Parceiro',
      Description: 'PRODEMO é um projeto cofinanciado pelo programa Direitos, Igualdade e Cidadania (REC) da União Europeia, para melhorar a consciência dos direitos de cidadania da UE e a inclusão dos cidadãos da UE em termos de mobilidade.',
    },
    IntroSettings: {
      GenralInfo: 'Informações gerais',
      AppLang: 'Idioma da aplicação',
      ChooseCountry: 'Escolher um país',
      ChangeCountry: 'Mudar país',
      Activate: 'Ativar',
      Deactivate: 'Desativar',
    },
    NoNotifications: 'Nenhuma notificação',
    WalkThrough: {
      Skip: 'Saltar',
      TitleFirst: 'Selecione o seu país',
      TitleSecond: 'Descubra os eventos',
      ContentSecond: 'Escolha os seus interesses e participe',
      TitleThird: 'Fique atento!',
      GetStarted: 'Iniciar',
    },
    ShareLink: 'Descarregue a App PRODEMO e saiba mais',
    SignIn: {
      Email: 'E-mail',
      Password: 'Palavra-passe',
      ForgotPassword: 'Esqueceu-se da palavra-passe?',
      Or: 'ou',
      SignFacebook: 'Inicie sessão com o Facebook',
      SignGoogle: 'Inicie sessão com o Google',
      SignApple: 'Inicie sessão com a Apple',
      Cancel: 'Cancelar',
      SignIn: 'Iniciar sessão',
      SignUp: 'Efetuar registo',
      NotAccount: 'Não tem uma conta? Efetue o registo',
      NoInfoTitle: 'Algo correu mal!',
    },
    SignUp: {
      ChooseRegion: 'Escolha uma região…',
      ValidationErrorTitle: 'Erro de validação!',
      PasswordShort: 'A sua palavra-passe deve ter pelo menos 6 carateres',
      ValidationErrorMessage: 'Algo correu mal. Verifique os seus dados ou retroceda e tente efetuar o registo.',
      JoinTitle: 'Bem-vindo à PRODEMO!',
      JoinMessage: 'Efetue o registo e envolva-se na comunidade europeia!',
      Username: 'Nome de utilizador',
      Policy_1: 'Li e aceito',
      Policy_2: 'política de privacidade',
      Policy_Url: 'https://www.prodemo-europa.eu/app-privacy-policy/',
    },
    ForgotPassword: {
      Text: 'Não se preocupe! Iremos ajudá-lo a recuperar a sua palavra-passe 🔑',
      SendEmail: 'Enviar e-mail',
      ConfirmationSent: 'Confirmação enviada',
      Confirmation_1: 'Enviamos um e-mail para',
      Confirmation_2: 'com uma ligação para repor a palavra-passe',
      Wrong_1: 'Certifique-se que',
      Wrong_2: 'é o endereço de e-mail correto ou que está associado a uma conta existente',
    },
    ResetPassword: {
      RePassword: 'Repor palavra-passe',
      Title: 'Repor palavra-passe',
      Text: 'Insira a sua nova palavra-passe 🔑',
      Button: 'Definir nova palavra-passe',
      ErrorText: 'Preencha ambos os campos com a mesma palavra-passe e tente novamente',
    },
    EmailPasswordSuccess: {
      Password: 'Palavra-passe alterada!',
      PasswordText: 'Obrigado 🎉 a sua palavra-passe foi reposta!',
      Email: 'E-mail verificado!',
      EmailText: 'Obrigado 🎉 o seu e-mail foi confirmado!',
      BackHome: 'Regressar à Página Inicial',
    },
    Profile: {
      Welcome: 'Bem-vindo',
    },
    Report: {
      TextTop: 'Pode reportar diretamente determinadas violações de um evento individual ou de um questionário, incluindo: spam, conteúdo abusivo ou nocivo, anúncios inapropriados, notícias autodestrutivas ou falsas.',
      Title: 'Reportar violação',
      Type: 'Insira a sua mensagem',
      Send: 'Enviar relatório',
      MessageSent: 'Mensagem enviada! Um administrador irá verificar o seu relatório.',
    },
  },
  pl: {
    Countries: {
      italy: 'Włochy',
      portugal: 'Portugalia',
      belgium: 'Belgia',
    },
    Menu: {
      Home: 'Strona główna',
      Articles: 'Artykuły',
      Events: 'Wydarzenia',
      Surveys: 'Sondaże',
      Info: 'Informacje o projekcie',
      Settings: 'Ustawienia',
      Footer: 'Współfinansowany przez program Unii Europejskiej „Prawa, równość i obywatelstwo”',
      Notifications: 'Powiadomienia',
      Profile: 'Profil',
      SignIn: 'Zaloguj się/Zarejestruj się',
      Logout: 'Logout',
      AddEvent: 'Utwórz wydarzenie',
      AddSurvey: 'Utwórz sondaż',
      Sign_in: 'Zaloguj się',
      Sign_up: 'Zarejestruj się',
      Forgot_password: 'Nie pamiętasz hasła?',
      Reset_password: 'Zresetuj hasło',
      Reset_password_success: 'Zresetuj hasło',
    },
    Home: {
      ReadLastArticles: 'Przeczytaj ostatnie artykuły',
      GetInvolved: 'Weź udział w wydarzeniach mających miejsce w Twoim kraju',
      ExploreEvents: 'Odkryj wszystkie wydarzenia',
      ExploreSurveys: 'Sondaże',
      ReadMore: 'Dowiedz się więcej...',
    },
    Article: {
      Article: 'Artykuł',
      NoArticles: 'Brak artykułów dla tego kraju',
      AlertTitle: 'Ten artykuł dotyczy kraju innego niż wybrany',
      AlertMessage: 'Jeżeli chcesz widzieć ten artykuł na liście, zmień kraj w swoich ustawieniach',
    },
    Event: 'Wydarzenie',
    Events: {
      Map: 'Mapa',
      Calendar: 'Kalendarz',
      User: 'Twoje wydarzenia',
      LocaleConfig: {
        monthNames: [
          'Styczeń',
          'Luty',
          'Marzec',
          'Kwiecień',
          'Maj',
          'Czerwiec',
          'Lipiec',
          'Sierpień',
          'Wrzesień',
          'Październik',
          'Listopad',
          'Grudzień',
        ],
        monthNamesShort: [
          'Sty',
          'Lut',
          'Mar',
          'Kwi',
          'Maj',
          'Cze',
          'Lip',
          'Sie',
          'Wrz',
          'Paź',
          'Lis',
          'Gru',
        ],
        dayNames: [
          'Niedziela',
          'Poniedziałek',
          'Wtorek',
          'Środa',
          'Czwartek',
          'Piątek',
          'Sobota',
        ],
        dayNamesShort: [
          'Nie',
          'Pon',
          'Wto',
          'Śro',
          'Czw',
          'Pią',
          'Sob',
        ],
      },
      NoEventsAll: 'Brak wydarzeń dla tego kraju',
      NoEvents: 'Brak wydarzeń w tym terminie',
      CheckLink: 'Otwórz link',
      AlertTitle: 'To wydarzenie dotyczy kraju innego niż wybrany',
      AlertMessage: 'Aby w przyszłości widzieć to wydarzenie na swojej liście, zmień kraj w ustawieniach',
      CheckPermissions: 'Odmowa zezwolenia',
      PermissionInstructions: 'Wygląda na to, że odmówiono Ci prawa dostępu do Kalendarza. Przejdź do opcji Ustawienia -> PRODEMO i przed zapisaniem zdarzenia aktywuj zezwolenia dla Kalendarza',
      AddToCalendarTitle: 'Dodaj to wydarzenie do kalendarza',
      AddToCalendarSub: 'Chcesz dodać to wydarzenie do swojego kalendarza?',
      RemoveFromCalendarTitle: 'Usuń z kalendarza',
      RemoveFromCalendarSub: 'Chcesz usunąć to wydarzenie ze swojego kalendarza?',
      EventTypeUser: 'Wydarzenie - uczestnik',
      EventTypeAdmin: 'Wydarzenie - administrator',
      EventStatusPending: 'Status: oczekiwanie na akceptację',
      EventStatusRejected: 'Status: Niezaakceptowany',
      AddEvent: 'Utwórz wydarzenie',
      CreateEvent: {
        Header: 'Zaproponuj nowe wydarzenie',
        Date: 'Data',
        Title: 'Nazwa',
        Abstract: 'Krótki opis',
        Description: 'Długi opis',
        Address: 'Adres, Miasto, Kraj',
        Link: 'Link',
        Submit: 'Wyślij',
        EventCreated: 'Wydarzenie zostało utworzone!',
        SubmitText: 'Jeżeli klikniesz na link "Wyślij", Twoje wydarzenie zostanie wysłane do administratora i poddane weryfikacji. Możesz sprawdzić status zapytania w zakładce Wydarzenia -> Twoje wydarzenia.',
        DatePicker: 'Wybierz datę',
        DatePickerCancel: 'Anuluj',
        DatePickerConfirm: 'Potwierdź',
      },
      OpenOnMaps: 'Otwórz w Google Maps',
    },
    Surveys: {
      Answers: 'Odpowiedzi',
      Vote: 'Ocena',
      Votes: 'Oceny',
      Survey: 'Sondaż',
      List: 'Wszystkie sondaże',
      User: 'Twoje sondaże',
      PickAnswer: 'Wybierz swą odpowiedź',
      AlreadyVoted: 'Już przyznałeś ocenę',
      AddSurvey: {
        Add: 'Dodaj nowy',
        Header: 'Utwórz nowy sondaż',
        Answer: 'Odpowiedź',
        AddAnswer: 'Dodaj odpowiedź',
        SurveyCreated: 'Sondaż został utworzony!',
        SubmitText: 'Jeżeli klikniesz na link "Wyślij", Twój sondaż zostanie wysłany do administratora i poddany weryfikacji. Możesz sprawdzić status zapytania w zakładce Sondaże -> Twoje sondaże',
      },
    },
    Info: {
      TheProject: 'Projekt',
      ProjPartners: 'Partner',
      Description: 'PRODEMO jest projektem współfinansowanym przez program Unii Europejskiej Prawa, Równość i Obywatelstwo (Rights, Equality and Citizenship - REC), którego celem jest poprawa świadomości praw obywatelskich UE oraz integracja przemieszczających się obywateli UE.',
    },
    IntroSettings: {
      GenralInfo: 'Informacje ogólne',
      AppLang: 'Język aplikacji',
      ChooseCountry: 'Wybierz kraj',
      ChangeCountry: 'Zmień kraj',
      Activate: 'Aktywuj',
      Deactivate: 'Dezaktywuj',
    },
    NoNotifications: 'Brak powiadomień',
    WalkThrough: {
      Skip: 'Pomiń',
      TitleFirst: 'Wybierz swój kraj',
      TitleSecond: 'Odkryj wydarzenia',
      ContentSecond: 'Wybierz to, na czym Ci zależy i zaangażuj się',
      TitleThird: 'Bądź na bieżąco!',
      GetStarted: 'Zacznij działać',
    },
    ShareLink: 'Pobierz aplikację PRODEMO i dowiedz się więcej',
    SignIn: {
      Email: 'Email',
      Password: 'Hasło',
      ForgotPassword: 'Nie pamiętasz hasła?',
      Or: 'lub',
      SignFacebook: 'Użyj konta Facebook',
      SignGoogle: 'Użyj konta Google',
      SignApple: 'Użyj konta Apple',
      Cancel: 'Anuluj',
      SignIn: 'Zaloguj się',
      SignUp: 'Zarejestruj się',
      NotAccount: 'Nie masz jeszcze konta? Zarejestruj się ',
      NoInfoTitle: 'Coś się nie powiodło!',
    },
    SignUp: {
      ChooseRegion: 'Wybierz region…',
      ValidationErrorTitle: 'Uwaga!',
      PasswordShort: 'Twoje hasło musi zawierać min. 6 znaków',
      ValidationErrorMessage: 'Coś się nie powiodło! Sprawdź wpisane dane lub spróbuj wejść',
      JoinTitle: 'Witaj w PRODEMO!',
      JoinMessage: 'Zarejestruj się i zostań aktywnym członkiem europejskiej wspólnoty!',
      Username: 'Nazwa użytkownika',
      Policy_1: 'Zapoznałem się i akceptuję treść',
      Policy_2: 'polityki prywatności',
      Policy_Url: 'https://www.prodemo-europa.eu/app-privacy-policy/',
    },
    ForgotPassword: {
      Text: 'Nie martw się! Pomożemy Ci odzsykać hasło 🔑',
      SendEmail: 'Wyślij email',
      ConfirmationSent: 'Potwierdzenie zostało wysłane',
      Confirmation_1: 'Wysłaliśmy email na adres',
      Confirmation_2: 'z linkiem umożliwiającym zresetowanie hasła',
      Wrong_1: 'Upewnij się, że podany adres',
      Wrong_2: 'jest prawidłowy i nie jest przypisany do istniejącego już konta',
    },
    ResetPassword: {
      RePassword: 'Powtórz hasło',
      Title: 'Zresetuj hasło',
      Text: 'Wpisz nowe hasło 🔑',
      Button: 'Ustaw nowe hasło',
      ErrorText: 'Wypełnij oba pola przy użyciu tego samego hasła i spróbuj ponownie',
    },
    EmailPasswordSuccess: {
      Password: 'Hasło zostało zmienione',
      PasswordText: 'Dziękujemy 🎉 Twoje hasło zostało zresetowane',
      Email: 'Adres email został zweryfikowany',
      EmailText: 'Dziękujemy 🎉 Twój adres email został potwierdzony!',
      BackHome: 'Wróć do strony głównej',
    },
    Profile: {
      Welcome: 'Witaj  ',
    },
    Report: {
      TextTop: 'Możesz zgłosić bezpośrednio, w ramach danego wydarzenia lub sondażu, naruszenie zasad, a tym: spam, niewłaściwe lub szkodliwe treści, nieodpowiednie ogłoszenia, działania autodestrukcyjne lub fake news.',
      Title: 'Zgłoś naruszenie',
      Type: 'Napisz wiadomość',
      Send: 'Wyślij zgłoszenie',
      MessageSent: 'Wiadomość została wysłana! Administrator zweryfikuje Twoje zgłoszenie',
    },
  },
  ro: {
    Countries: {
      italy: 'Italia',
      portugal: 'Portugalia',
      belgium: 'Belgia',
    },
    Menu: {
      Home: 'Acasă',
      Articles: 'Articole',
      Events: 'Evenimente',
      Surveys: 'Sondaje',
      Info: 'Informații despre proiect',
      Settings: 'Setări',
      Footer: 'Cofinanțare din partea Programului Drepturi, Egalitate și Cetățenie în Uniunea Europeană',
      Notifications: 'Notificări',
      Profile: 'Profil',
      SignIn: 'Conectare/Înregistrare',
      Logout: 'Delogare',
      AddEvent: 'Creează eveniment',
      AddSurvey: 'Creează sondaj',
      Sign_in: 'Conectare',
      Sign_up: 'Înregistrare',
      Forgot_password: 'Am uitat parola',
      Reset_password: 'Resetează parola',
      Reset_password_success: 'Resetează parola',
    },
    Home: {
      ReadLastArticles: 'Citește ultimele articole',
      GetInvolved: 'Participă la evenimentele din țara ta',
      ExploreEvents: 'Descoperă toate evenimentele',
      ExploreSurveys: 'Sondaje',
      ReadMore: 'Află mai multe…',
    },
    Article: {
      Article: 'Articol',
      NoArticles: 'Niciun articol pentru această țară',
      AlertTitle: 'Acest articol se referă la o altă țară decât cea pe care ai selectat-o',
      AlertMessage: 'Modifică țara în setările tale dacă dorești să vezi acest articol în listă',
    },
    Event: 'Eveniment',
    Events: {
      Map: 'Hartă',
      Calendar: 'Calendar',
      User: 'Evenimentele tale',
      LocaleConfig: {
        monthNames: [
          'Ianuarie',
          'Februarie',
          'Martie',
          'Aprilie',
          'Mai',
          'Iunie',
          'Iulie',
          'August',
          'Septembrie',
          'Octombrie',
          'Noiembrie',
          'Decembrie',
        ],
        monthNamesShort: [
          'Ian',
          'Feb',
          'Mar',
          'Apr',
          'Mai',
          'Iun',
          'Iul',
          'Aug',
          'Sep',
          'Oct',
          'Nov',
          'Dec',
        ],
        dayNames: [
          'Duminică',
          'Luni',
          'Marți',
          'Miercuri',
          'Joi',
          'Vineri',
          'Sâmbătă',
        ],
        dayNamesShort: [
          'Du',
          'Lu',
          'Ma',
          'Mi',
          'Jo',
          'Vi',
          'Sa',
        ],
      },
      NoEventsAll: 'Niciun eveniment pentru această țară',
      NoEvents: 'Niciun eveniment în această dată',
      CheckLink: 'Deschide link',
      AlertTitle: 'Acest eveniment se referă la o altă țară decât cea pe care ai selectat-o',
      AlertMessage: 'Modifică țara în setări pentru a vedea acest eveniment în lista ta în viitor.',
      CheckPermissions: 'Permisiune negată',
      PermissionInstructions: 'Se pare că ți-a fost refuzată permisiunea de a accesa Calendarul. Du-te în Setări -> PRODEMO și activează permisiunile legate de Calendar înainte de a salva evenimentul.',
      AddToCalendarTitle: 'Adaugă acest eveniment în calendar',
      AddToCalendarSub: 'Vrei să adaugi acest eveniment în calendarul tău?',
      RemoveFromCalendarTitle: 'Șterge din calendar',
      RemoveFromCalendarSub: 'Vrei să ștergi acest eveniment din calendarul tău?',
      EventTypeUser: 'Eveniment utilizator',
      EventTypeAdmin: 'Eveniment administrator',
      EventStatusPending: 'Stare: se așteaptă aprobarea',
      EventStatusRejected: 'Refuzată',
      AddEvent: 'Creează eveniment',
      CreateEvent: {
        Header: 'Propune un eveniment nou',
        Date: 'Dată',
        Title: 'Titlu',
        Abstract: 'Descriere scurtă',
        Description: 'Descriere detaliată',
        Address: 'Adresă, Oraș, Țară',
        Link: 'Link',
        Submit: 'Trimite',
        EventCreated: 'Eveniment creat!',
        SubmitText: 'Făcând clic pe „Trimite”, evenimentul tău va fi trimis unui administrator pentru revizuire. Poți verifica starea acestuia în pagina Evenimente-> Evenimentele tale.',
        DatePicker: 'Alege o dată',
        DatePickerCancel: 'Anulează',
        DatePickerConfirm: 'Confirmă',
      },
      OpenOnMaps: 'Deschide în Google Maps',
    },
    Surveys: {
      Answers: 'Răspunsuri',
      Vote: 'Vot',
      Votes: 'Voturi',
      Survey: 'Sondaj',
      List: 'Toate sondajele',
      User: 'Sondajele tale',
      PickAnswer: 'Alege un răspuns',
      AlreadyVoted: 'Ți-ai exprimat deja votul',
      AddSurvey: {
        Add: 'Creează nou',
        Header: 'Creează un sondaj nou',
        Answer: 'Răspuns',
        AddAnswer: 'Adaugă răspuns',
        SurveyCreated: 'Sondaj creat!',
        SubmitText: 'Făcând clic pe „Trimite”, evenimentul tău va fi trimis unui administrator pentru revizuire. Poți verifica starea acestuia în pagina Sondaje-> Sondajele tale.',
      },
    },
    Info: {
      TheProject: 'Proiectul',
      ProjPartners: 'Partener',
      Description: 'PRODEMO este un proiect cofinanțat de programul Drepturi, Egalitate și Cetățenie (REC) al Uniunii Europene, pentru a îmbunătăți gradul de conștientizare a drepturilor cetățeniei UE și includerea cetățenilor UE în mișcare.',
    },
    IntroSettings: {
      GenralInfo: 'Informații generale',
      AppLang: 'Limba aplicației',
      ChooseCountry: 'Alege o țară',
      ChangeCountry: 'Schimbă țara',
      Activate: 'Activează',
      Deactivate: 'Dezactivează',
    },
    NoNotifications: 'Nicio notificare',
    WalkThrough: {
      Skip: 'Omite',
      TitleFirst: 'Selectează țara ta',
      TitleSecond: 'Descoperă evenimentele',
      ContentSecond: 'Alege lucrurile de care îți pasă și implică-te',
      TitleThird: 'Fii pe fază!',
      GetStarted: 'Începe',
    },
    ShareLink: 'Descarcă aplicația PRODEMO și află mai multe',
    SignIn: {
      Email: 'E-mail',
      Password: 'Parolă',
      ForgotPassword: 'Ai uitat parola?',
      Or: 'o',
      SignFacebook: 'Conectează-te cu Facebook',
      SignGoogle: 'Conectează-te cu Google',
      SignApple: 'Conectează-te cu Apple',
      Cancel: 'Anulează',
      SignIn: 'Conectează-te',
      SignUp: 'Înregistrează-te',
      NotAccount: 'Nu ai încă cont? Înregistrează-te',
      NoInfoTitle: 'Ceva nu a funcționat!',
    },
    SignUp: {
      ChooseRegion: 'Alege un motiv...',
      ValidationErrorTitle: 'Atenție!',
      PasswordShort: 'Parola ta trebuie să conțină cel puțin 6 caractere',
      ValidationErrorMessage: 'Ceva nu a funcționat! Verifică-ți datele sau încearcă să te conectezi.',
      JoinTitle: 'Bine ai venit pe PRODEMO!',
      JoinMessage: 'Înregistrează-te și participă la comunitatea europeană!',
      Username: 'Nume utilizator',
      Policy_1: 'Am citit și accept',
      Policy_2: 'politica de confidențialitate',
      Policy_Url: 'https://www.prodemo-europa.eu/app-privacy-policy/',
    },
    ForgotPassword: {
      Text: 'Nu-ți fă griji! Te vom ajuta să-ți recuperezi parola 🔑',
      SendEmail: 'Trimite e-mail',
      ConfirmationSent: 'Confirmare trimisă!',
      Confirmation_1: 'Am trimis un e-mail la adresa',
      Confirmation_2: 'cu un link pentru resetarea parolei',
      Wrong_1: 'Asigură-te că adresa',
      Wrong_2: 'este corectă și că este asociată unui cont existent',
    },
    ResetPassword: {
      RePassword: 'Reintrodu parola',
      Title: 'Resetare parolă',
      Text: 'Introdu o parolă nouă 🔑',
      Button: 'Setează parolă nouă',
      ErrorText: 'Completează ambele câmpuri cu aceeași parolă și încearcă din nou',
    },
    EmailPasswordSuccess: {
      Password: 'Parolă schimbată',
      PasswordText: 'Mulțumesc 🎉 parola ta a fost resetată!',
      Email: 'E-mail verificat!',
      EmailText: 'Mulțumesc  🎉 adresa ta de e-mail a fost confirmată!',
      BackHome: 'Întoarce-te la home',
    },
    Profile: {
      Welcome: 'Bine ai venit',
    },
    Report: {
      TextTop: 'Poți semnala direct printr-un singur eveniment sau sondaj anumite încălcări ale regulamentului, cum ar fi: spam, mesaje abuzive sau nocive, anunțuri nepotrivite, autolezionism și fake news. ',
      Title: 'Semnalează o încălcare a regulamentului',
      Type: 'Scrie mesaj',
      Send: 'Trimite sesizare',
      MessageSent: 'Mesaj trimis! Un administrator îți va verifica sesizarea.',
    },
  },
  bg: {
    Countries: {
      italy: 'Италия',
      portugal: 'Португалия',
      belgium: 'Белгия',
    },
    Menu: {
      Home: 'Начален екран',
      Articles: 'Статии',
      Events: 'Събития',
      Surveys: 'Анкети',
      Info: 'Информация за проекта',
      Settings: 'Настройки',
      Footer: 'Съфинансиран от Програмата за права, равенство и гражданство на Европейския съюз',
      Notifications: 'Известия',
      Profile: 'Профил',
      SignIn: 'Вход/Регистрация',
      Logout: 'Изход от системата',
      AddEvent: 'Създай събитие',
      AddSurvey: 'Създай анкета',
      Sign_in: 'Вход',
      Sign_up: 'Регистрация',
      Forgot_password: 'Забравена парола',
      Reset_password: 'Нова парола',
      Reset_password_success: 'Нова парола',
    },
    Home: {
      ReadLastArticles: 'Прочетете последните статии',
      GetInvolved: 'Посещавайте събития във вашата страна',
      ExploreEvents: 'Открийте всички събития',
      ExploreSurveys: 'Анкети',
      ReadMore: 'Открийте повече…',
    },
    Article: {
      Article: 'Статия',
      NoArticles: 'Няма статия за тази държава',
      AlertTitle: 'Тази статия е за държава, различна от тази, която сте избрали',
      AlertMessage: 'Променете държавата в настройките си, ако искате да видите този елемент в списъка',
    },
    Event: 'Събитие',
    Events: {
      Map: 'Карта',
      Calendar: 'Календар',
      User: 'Вашите събития',
      LocaleConfig: {
        monthNames: [
          'януари',
          'февруари',
          'март',
          'април',
          'май',
          'юни',
          'юли',
          'август',
          'септември',
          'октомври',
          'ноември',
          'декември',
        ],
        monthNamesShort: [
          'ян.',
          'фев.',
          'март',
          'апр.',
          'май',
          'юни',
          'юли',
          'авг.',
          'септ.',
          'окт.',
          'ноем.',
          'дек.',
        ],
        dayNames: [
          'неделя',
          'понеделник',
          'вторник',
          'сряда',
          'четвъртък',
          'петък',
          'събота',
        ],
        dayNamesShort: [
          'неделя',
          'пон.',
          'вт.',
          'ср.',
          'четв.',
          'пет.',
          'съб.',
        ],
      },
      NoEventsAll: 'Няма събития за тази държава',
      NoEvents: 'Няма събития за тази дата',
      CheckLink: 'Отвори връзката',
      AlertTitle: 'Това събитие е за държава, различна от тази, която сте избрали',
      AlertMessage: 'Променете държавата в настройките, за да видите това събитие в списъка си в бъдеще.',
      CheckPermissions: 'Разрешението е отказано',
      PermissionInstructions: 'Изглежда, че ви е отказано разрешение за достъп до календара. Отидете в Настройки -> PRODEMO и активирайте разрешенията за календар, преди да запазите събитието.',
      AddToCalendarTitle: 'Добавете това събитие към календара',
      AddToCalendarSub: 'Искате ли да добавите това събитие към календара си?',
      RemoveFromCalendarTitle: 'Премахнете от календара',
      RemoveFromCalendarSub: 'Искате ли да премахнете това събитие от календара си?',
      EventTypeUser: 'Събитие на потребител',
      EventTypeAdmin: 'Събитие на администратор',
      EventStatusPending: 'Състояние: очаква одобрение',
      EventStatusRejected: 'Отхвърлено',
      AddEvent: 'Създай събитие',
      CreateEvent: {
        Header: 'Предложете ново събитие',
        Date: 'Дата',
        Title: 'Заглавие',
        Abstract: 'Кратко описание',
        Description: 'Подробно описание',
        Address: 'Адрес, Град, Страна',
        Link: 'Връзка',
        Submit: 'Изпрати',
        EventCreated: 'Събитието е създадено!',
        SubmitText: 'С кликването върху „Изпрати“ Вашето събитие ще бъде изпратено за преглед от администратор. Можете да проверявате неговото състояние на страницата Събития -> Вашите събития.',
        DatePicker: 'Изберете дата',
        DatePickerCancel: 'Отмяна',
        DatePickerConfirm: 'Потвърди',
      },
      OpenOnMaps: 'Отвори в Google Maps',
    },
    Surveys: {
      Answers: 'Отговори',
      Vote: 'Гласуване',
      Votes: 'Гласове',
      Survey: 'Анкета',
      List: 'Всички анкети',
      User: 'Вашите анкети',
      PickAnswer: 'Изберете Вашия отговор',
      AlreadyVoted: 'Вече сте гласували',
      AddSurvey: {
        Add: 'Създай нова',
        Header: 'Създайте нова анкета',
        Answer: 'Отговор',
        AddAnswer: 'Добави отговор',
        SurveyCreated: 'Анкетата е създадена!',
        SubmitText: 'С кликването върху „Изпрати“ Вашата анкета ще бъде изпратена за преглед от администратор. Можете да проверявате нейното състояние на страницата Анкети -> Вашите анкети.',
      },
    },
    Info: {
      TheProject: 'Проектът',
      ProjPartners: 'Партньор',
      Description: 'PRODEMO е проект, съфинансиран от Програмата за права, равенство и гражданство (REC) на Европейския съюз, за ​​подобряване на осведомеността относно правата на гражданството на ЕС и включването на гражданите на ЕС в движение.',
    },
    IntroSettings: {
      GenralInfo: 'Обща информация',
      AppLang: 'Език на приложението',
      ChooseCountry: 'Изберете държава',
      ChangeCountry: 'Променете държава',
      Activate: 'Активирайте',
      Deactivate: 'Деактивирайте',
    },
    NoNotifications: 'Няма известие',
    WalkThrough: {
      Skip: 'Прескочи',
      TitleFirst: 'Изберете вашата държава',
      TitleSecond: 'Открийте събитията',
      ContentSecond: 'Изберете това, което ви интересува, и се включете',
      TitleThird: 'Останете на линия!',
      GetStarted: 'Първи стъпки',
    },
    ShareLink: 'Изтеглете приложението PRODEMO и научете повече',
    SignIn: {
      Email: 'Имейл',
      Password: 'Парола',
      ForgotPassword: 'Забравена парола?',
      Or: 'или',
      SignFacebook: 'Вход с Facebook',
      SignGoogle: 'Вход с Google',
      SignApple: 'Вход с Apple',
      Cancel: 'Отмяна',
      SignIn: 'Вход',
      SignUp: 'Регистрация',
      NotAccount: 'Все още нямате акаунт? Регистрирайте се',
      NoInfoTitle: 'Нещо се обърка!',
    },
    SignUp: {
      ChooseRegion: 'Изберете област…',
      ValidationErrorTitle: 'Внимание!',
      PasswordShort: 'Паролата Ви трябва да съдържа минимум 6 знака',
      ValidationErrorMessage: 'Нещо се обърка! Проверете данните си или опитайте да влезете.',
      JoinTitle: 'Добре дошли на PRODEMO!',
      JoinMessage: 'Регистрирайте се и участвайте в Европейската общност!',
      Username: 'Потребителско име',
      Policy_1: 'Прочетох и приемам',
      Policy_2: 'политиката за поверителност',
      Policy_Url: 'https://www.prodemo-europa.eu/app-privacy-policy/',
    },
    ForgotPassword: {
      Text: 'Не се притеснявайте! Ще Ви помогнем да възстановите паролата си 🔑',
      SendEmail: 'Изпрати имейл',
      ConfirmationSent: 'Потвърди изпращането!',
      Confirmation_1: 'Изпратихме имейл съобщение на адрес',
      Confirmation_2: 'с връзка за възстановяване на паролата',
      Wrong_1: 'Уверете се, че адресът',
      Wrong_2: 'е правилен или че е свързан със съществуващ акаунт',
    },
    ResetPassword: {
      RePassword: 'Въведете отново паролата',
      Title: 'Смяна на паролата',
      Text: 'Въведете нова парола 🔑',
      Button: 'Задайте нова парола',
      ErrorText: 'Въведете същата парола и в двете полета и опитайте отново',
    },
    EmailPasswordSuccess: {
      Password: 'Паролата е променена',
      PasswordText: 'Благодарим Ви 🎉 паролата е променена!',
      Email: 'Имейлът е потвърден!',
      EmailText: 'Благодарим Ви 🎉 Вашият имейл беше потвърден!',
      BackHome: 'Към началото',
    },
    Profile: {
      Welcome: 'Добре дошли',
    },
    Report: {
      TextTop: 'Можете да сигнализирате директно от отделно събитие или анкета за нарушения, като например: спам, оскърбително или вредно съдържание, неприемлива реклама, самонараняване и фалшиви новини.',
      Title: 'Сигнал за нарушение',
      Type: 'Напишете съобщението си',
      Send: 'Изпрати сигнала',
      MessageSent: 'Съобщението е изпратено! Сигналът Ви ще бъде проверен от администратор.',
    },
  },
  de: {
    Countries: {
      italy: 'Italien',
      portugal: 'Portugal',
      belgium: 'Belgien',
    },
    Menu: {
      Home: 'Homepage',
      Articles: 'Artikel',
      Events: 'Events',
      Surveys: 'Umfragen',
      Info: 'Projektinformationen',
      Settings: 'Einstellungen',
      Footer: 'Kofinanziert durch das Programm „Rechte, Gleichheit und Unionsbürgerschaft“',
      Notifications: 'Meldungen',
      Profile: 'Profil',
      SignIn: 'Anmelden/Registrieren',
      Logout: 'Abmelden',
      AddEvent: 'Veranstaltung erstellen',
      AddSurvey: 'Umfrage erstellen',
      Sign_in: 'Anmelden',
      Sign_up: 'Registrieren',
      Forgot_password: 'Passwort vergessen',
      Reset_password: 'Passwort zurücksetzen',
      Reset_password_success: 'Passwort zurücksetzen',
    },
    Home: {
      ReadLastArticles: 'Lesen Sie die letzten Artikel',
      GetInvolved: 'Nehmen Sie an Events Ihres Landes teil',
      ExploreEvents: 'Entdecken Sie alle Events',
      ExploreSurveys: 'Umfragen',
      ReadMore: 'Mehr erfahren ...',
    },
    Article: {
      Article: 'Artikel',
      NoArticles: 'Kein Artikel für dieses Land',
      AlertTitle: 'Dieser Artikel betrifft ein anderes Land als das von Ihnen gewählte',
      AlertMessage: 'Ändern Sie das Land in Ihren Einstellungen, wenn Sie diesen Artikel in der Liste sehen möchten',
    },
    Event: 'Event',
    Events: {
      Map: 'Karte',
      Calendar: 'Kalender',
      User: 'Deine Veranstaltungen',
      LocaleConfig: {
        monthNames: [
          'Januar',
          'Februar',
          'März',
          'April',
          'Mai',
          'Juni',
          'Juli',
          'August',
          'September',
          'Oktober',
          'November',
          'Dezember',
        ],
        monthNamesShort: [
          'Jan.',
          'Feb.',
          'Mär.',
          'Apr.',
          'Mai',
          'Jun',
          'Jul',
          'Aug.',
          'Sep.',
          'Okt.',
          'Nov.',
          'Dez.',
        ],
        dayNames: [
          'Sonntag',
          'Montag',
          'Dienstag',
          'Mittwoch',
          'Donnerstag',
          'Freitag',
          'Samstag',
        ],
        dayNamesShort: [
          'So.',
          'Mo.',
          'Di.',
          'Mi.',
          'Do.',
          'Fr.',
          'Sa.',
        ],
      },
      NoEventsAll: 'Kein Event für dieses Land',
      NoEvents: 'Kein Event an diesem Datum',
      CheckLink: 'Link öffnen',
      AlertTitle: 'Dieses Event betrifft ein anderes Land als das von Ihnen gewählte',
      AlertMessage: 'Ändern Sie das Land in den Einstellungen, um dieses Event zukünftig in Ihrer Liste zu sehen.',
      CheckPermissions: 'Zugriff verweigert',
      PermissionInstructions: 'Es scheint, als würde Ihnen der Zugang zum Kalender verweigert Gehen Sie auf Einstellungen -> PRODEMO und schalten Sie vor dem Speichern des Events den Zugriff auf Calendar frei.',
      AddToCalendarTitle: 'Fügen Sie dieses Event in den Kalender ein',
      AddToCalendarSub: 'Möchten Sie dieses Event in Ihren Kalender aufnehmen?',
      RemoveFromCalendarTitle: 'Aus dem Kalender entfernen',
      RemoveFromCalendarSub: 'Möchten Sie dieses Event aus Ihrem Kalender entfernen?',
      EventTypeUser: 'Nutzer-Veranstaltung',
      EventTypeAdmin: 'Administrator-Veranstaltung',
      EventStatusPending: 'Status: Genehmigung ausstehend',
      EventStatusRejected: 'Abgelehnt',
      AddEvent: 'Veranstaltung erstellen',
      CreateEvent: {
        Header: 'Eine Veranstaltung vorschlagen',
        Date: 'Datum',
        Title: 'Titel',
        Abstract: 'Kurze Beschreibung',
        Description: 'lange Beschreibung',
        Address: 'Anschrift, Stadt, Land',
        Link: 'Link',
        Submit: 'Senden',
        EventCreated: 'Veranstaltung erstellt!',
        SubmitText: 'Wenn Sie auf "Senden" klicken, wird Ihre Veranstaltung zur Überprüfung an einen Administrator gesendet. Sie können den Status auf der Seite Veranstaltungen -> Ihre Veranstaltungen überprüfen.',
        DatePicker: 'Datum wählen',
        DatePickerCancel: 'Abbrechen',
        DatePickerConfirm: 'Bestätigen',
      },
      OpenOnMaps: 'In Google Maps öffnen',
    },
    Surveys: {
      Answers: 'Antworten',
      Vote: 'Stimme',
      Votes: 'Stimmen',
      Survey: 'Umfrage',
      List: 'Alle Umfragen',
      User: 'Ihre Umfragen',
      PickAnswer: 'Wählen Sie Ihre Antwort',
      AlreadyVoted: 'Sie haben bereits Ihre Stimme abgegeben',
      AddSurvey: {
        Add: 'Neu erstellen',
        Header: 'Neue Umfrage erstellen',
        Answer: 'Antwort',
        AddAnswer: 'Antwort hinzufügen',
        SurveyCreated: 'Umfrage erstellt!',
        SubmitText: 'Wenn Sie auf "Senden" klicken, wird Ihre Umfrage zur Überprüfung an einen Administrator gesendet. Sie können den Status auf der Seite Umfragen -> Ihre Umfragen überprüfen.',
      },
    },
    Info: {
      TheProject: 'Das Projekt',
      ProjPartners: 'Partner',
      Description: 'PRODEMO ist ein vom Programm „Rechte, Gleichheit und Unionsbürgerschaft (REC)“ kofinanziertes Programm zur Sensibilisierung der Öffentlichkeit für die Unionsbürgerrechte und Integration von in Mobilität befindlichen EU-Bürgern.',
    },
    IntroSettings: {
      GenralInfo: 'Allgemeine Informationen',
      AppLang: 'Sprache der Anwendung',
      ChooseCountry: 'Land auswählen',
      ChangeCountry: 'Land ändern',
      Activate: 'Aktivieren',
      Deactivate: 'Deaktivieren',
    },
    NoNotifications: 'Keine Meldung',
    WalkThrough: {
      Skip: 'Überspringen',
      TitleFirst: 'Wählen Sie Ihr Land aus',
      TitleSecond: 'Entdecken Sie die Events',
      ContentSecond: 'Wählen Sie aus, was Sie interessiert, und machen Sie mit',
      TitleThird: 'Bleiben Sie dran!',
      GetStarted: 'Starten Sie',
    },
    ShareLink: 'Laden Sie die PROMEDO-App herunter und erfahren Sie mehr',
    SignIn: {
      Email: 'E-Mail',
      Password: 'Passwort',
      ForgotPassword: 'Passwort vergessen?',
      Or: 'oder',
      SignFacebook: 'Mit Facebook anmelden',
      SignGoogle: 'Mit Google anmelden',
      SignApple: 'Mit Apple anmelden',
      Cancel: 'Abbrechen',
      SignIn: 'Anmelden',
      SignUp: 'Registrieren',
      NotAccount: 'Sie haben noch kein Konto? Registrieren',
      NoInfoTitle: 'Es ist etwas schief gelaufen!',
    },
    SignUp: {
      ChooseRegion: 'Ein Bundesland wählen...',
      ValidationErrorTitle: 'Achtung!',
      PasswordShort: 'Ihr Passwort muss mindestens 6 Zeichen lang sein',
      ValidationErrorMessage: 'Es ist etwas schief gelaufen! Prüfen Sie Ihre Daten oder versuchen Sie, sich anzumelden.',
      JoinTitle: 'Herzlich Willkommen bei PRODEMO!',
      JoinMessage: 'Registrieren Sie sich und nehmen an der Europäischen Union teil!',
      Username: 'Benutzername',
      Policy_1: 'Ich habe die Datenschutzbestimmungen',
      Policy_2: 'gelesen und zur Kenntnis genommen',
      Policy_Url: 'https://www.prodemo-europa.eu/app-privacy-policy/',
    },
    ForgotPassword: {
      Text: 'Machen Sie sich keine Sorgen! Wir helfen Ihnen, Ihr Passwort wiederherzustellen 🔑.',
      SendEmail: 'E-Mail senden',
      ConfirmationSent: 'Bestätigung gesendet!',
      Confirmation_1: 'Wir haben Ihnen eine E-Mail mit einem Link',
      Confirmation_2: 'zum Zurücksetzen des Passworts gesendet',
      Wrong_1: 'Sicherstellen, dass die Adresse korrekt ',
      Wrong_2: 'oder mit einem bestehenden Konto verbunden ist.',
    },
    ResetPassword: {
      RePassword: 'Passwort erneut eingeben',
      Title: 'Passwort zurücksetzen',
      Text: 'Ein neues Passwort eingeben 🔑',
      Button: 'Neues Passwort festlegen',
      ErrorText: 'In beide Felder das selbe Passwort eingeben und erneut versuchen.',
    },
    EmailPasswordSuccess: {
      Password: 'Das Passwort wurde geändert',
      PasswordText: 'Vielen Dank 🎉 Ihr Passwort wurde zurückgesetzt!',
      Email: 'E-Mail bestätigt!',
      EmailText: 'Vielen Dank 🎉 Ihre E-Mail wurde bestätigt!',
      BackHome: 'Zurück zur Startseite',
    },
    Profile: {
      Welcome: 'Willkommen',
    },
    Report: {
      TextTop: 'Sie können bestimmte Verstöße direkt von einem einzelnen Ereignis oder einer Umfrage aus melden, darunter: Spam, missbräuchliche oder schädliche Inhalte, unangemessene Werbung, Selbstschädigung und Fake News.',
      Title: 'Einen Verstoß melden',
      Type: 'Schreiben Sie Ihre Nachricht',
      Send: 'Meldung senden',
      MessageSent: 'Nachricht versandt! Ein Administrator wird Ihre Meldung prüfen.',
    },
  },
}

export default LABELS
