const ROUTES = {
  WalkThrough: 'WalkThrough',
  IntroScreen: 'IntroScreen',
  Login: 'Login',
  SignInStack: 'SignInStack',
  SignIn: 'SignIn',
  SignUp: 'SignUp',
  ForgotPassword: 'ForgotPassword',
  ResetPassword: 'ResetPassword',
  ResetPasswordSuccess: 'ResetPasswordSuccess',
  Profile: 'Profile',
  SurveyList: 'SurveyList',
  MainPageStack: 'MainPageStack',
  MainPage: 'MainPage',
  ProjectInfos: 'ProjectInfos',
  Settings: 'Settings',
  ArticleList: 'ArticleList',
  ArticleSingle: 'ArticleSingle',
  EventsTopNavigator: 'EventsTopNavigator',
  EventListMap: 'EventListMap',
  EventListCalendar: 'EventListCalendar',
  EventSingle: 'EventSingle',
  AddEvent: 'AddEvent',
  EventListUser: 'EventListUser',
  SurveysTopNavigator: 'SurveysTopNavigator',
  SurveyList: 'SurveyList',
  SurveyListUser: 'SurveyListUser',
  SurveySingle: 'SurveySingle',
  AddSurvey: 'AddSurvey',
  DrawerNavigator: 'DrawerNavigator',
  DrawerStack: 'DrawerStack',
  Notifications: 'Notifications',
}
export default ROUTES
